web/router.ex
defmodule Formerer.Router do
  use Formerer.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :authenticate_user do
    plug Formerer.UserAuthentication
  end

  pipeline :activated_account do
    plug Formerer.AccountActivation
  end

  scope "/form", Formerer do
    pipe_through :api

    post "/:slug", FormSubmissionsController, :create
  end

  scope "/", Formerer do
    pipe_through [:browser, :protect_from_forgery]

    get "/", PageController, :index

    get "/register", UsersController, :new
    post "/register", UsersController, :create

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete
    resources "/account_activation", AccountActivationController, only: [:edit]
    resources "/password_reset", PasswordResetController, only: [:new, :create, :edit, :update]

    pipe_through :authenticate_user
    get "/dashboard", DashboardController, :index
    pipe_through :activated_account
    resources "/users", UsersController, only: [:edit, :update]

    resources "/forms", FormsController, only: [:new, :create, :update, :show, :delete] do
      get "/columns/edit", FormColumnsController, :edit
      post "/columns/update", FormColumnsController, :update
    end

    get "/forms/:form_id/settings", FormSettingsController, :edit

  end

  if Mix.env == :dev do
      scope "/dev" do
      pipe_through [:browser]

      forward "/mailbox", Plug.Swoosh.MailboxPreview, [base_path: "/dev/mailbox"]
    end
  end

end

web/models/session.ex
defmodule Formerer.Session do
  import Comeonin.Bcrypt, only: [checkpw: 2]
  import Plug.Conn
  alias Formerer.User
  alias Formerer.Repo

  def login(params) do
    user = Repo.get_by(User, email: String.downcase(params["email"]))
    case authenticate(user, params["password"]) do
      true -> {:ok, user}
      _ -> :error
    end
  end

  def current_user(conn) do
    case conn.assigns[:user] do
      nil ->
        id = get_session(conn, :current_user)
        if id do
          user = Repo.get(User, id)
          token = Phoenix.Token.sign(conn, "user socket", user.id)
          conn
          |> assign(:user, user)
          |> assign(:user_token, token)
          user
        end
      user ->
        user
    end
  end

  def logged_in?(conn), do: !!current_user(conn)

  defp authenticate(user, password) do
    case user do
      nil -> false
      _ -> checkpw(password, user.password_digest)
    end
  end
end

web/controllers/session_controller.ex
defmodule Formerer.SessionController do
  use Formerer.Web, :controller

  def new(conn, _) do
    render conn, "new.html"
  end

  def create(conn, %{"session" => session_params}) do
    case Formerer.Session.login(session_params) do
      {:ok, user} ->
        conn
        |> put_session(:current_user, user.id)
        |> put_flash(:info, "Welcome back!")
        |> redirect(to: dashboard_path(conn, :index))
      :error ->
        conn
        |> put_flash(:info, "Wrong email or password")
        |> render("new.html")
    end
  end

  def delete(conn, _) do
    conn
    |> delete_session(:current_user)
    |> put_flash(:info, "Logged out")
    |> redirect(to: "/")
  end

end

web/views/session_view.ex
defmodule Formerer.SessionView do
  use Formerer.Web, :view
end

web/templates/session/new.html.eex
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--4-col"></div>
  <div class="mdl-cell mdl-card mdl-shadow--2dp mdl-cell--4-col">
    <div class="mdl-card__title">
      <h2 class="mdl-card__title-text">Login</h2>
    </div>

    <div class="mdl-card__supporting-text">

      <%= form_for @conn, session_path(@conn, :create), [as: :session], fn f -> %>

        <div class='mdl-textfield mdl-js-textfield'>
          <%= email_input f, :email, class: "mdl-textfield__input" %>
          <label class='mdl-textfield__label'>Email</label>
        </div>

        <div class='mdl-textfield mdl-js-textfield'>
          <%= password_input f, :password, class: "mdl-textfield__input" %>
          <label class='mdl-textfield__label'>Password</label>
        </div>

        <%= submit "Login", class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
      <% end %>

      <%= link "forgot my password", to: password_reset_path(@conn, :new), class: "mdl-button mdl-js-button mdl-js-ripple-effect" %>

    </div>
  </div>
</div>