web/router.ex
defmodule Formerer.Router do
  use Formerer.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :authenticate_user do
    plug Formerer.UserAuthentication
  end

  pipeline :activated_account do
    plug Formerer.AccountActivation
  end

  scope "/form", Formerer do
    pipe_through :api

    post "/:slug", FormSubmissionsController, :create
  end

  scope "/", Formerer do
    pipe_through [:browser, :protect_from_forgery]

    get "/", PageController, :index

    get "/register", UsersController, :new
    post "/register", UsersController, :create

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete
    resources "/account_activation", AccountActivationController, only: [:edit]
    resources "/password_reset", PasswordResetController, only: [:new, :create, :edit, :update]

    pipe_through :authenticate_user
    get "/dashboard", DashboardController, :index
    pipe_through :activated_account
    resources "/users", UsersController, only: [:edit, :update]

    resources "/forms", FormsController, only: [:new, :create, :update, :show, :delete] do
      get "/columns/edit", FormColumnsController, :edit
      post "/columns/update", FormColumnsController, :update
    end

    get "/forms/:form_id/settings", FormSettingsController, :edit

  end

  if Mix.env == :dev do
      scope "/dev" do
      pipe_through [:browser]

      forward "/mailbox", Plug.Swoosh.MailboxPreview, [base_path: "/dev/mailbox"]
    end
  end

end

web/controllers/form_columns_controller.ex
defmodule Formerer.FormColumnsController do
  use Formerer.Web, :controller
  import Formerer.Session, only: [current_user: 1]
  import Formerer.UserFormRetriever, only: [get_user_form: 2]
  import Formerer.FormColumnsUpdater
  import Ecto.Query
  alias Formerer.{Submission, Repo}

  def edit(conn, %{"forms_id" => id}) do
    case current_user(conn) |> get_user_form(id) do
      { :ok, form } ->
        submission = first_submission(form)
        conn
        |> put_layout(false)
        |> render("edit.html", form: form, submission: submission)
      { :error, error } ->
        send_resp(conn, 404, error)
    end
  end

  def update(conn, %{"columns" => columns, "forms_id" => id}) do
    case current_user(conn) |> get_user_form(id) do
      { :ok, form } ->
        form_columns_update(conn, form, columns)
      { :error, error } ->
        send_resp(conn, 404, error)
    end
  end

  defp first_submission(form) do
    Submission |> where(form_id: ^form.id) |> limit(1) |> Repo.one
  end

  defp form_columns_update(conn, form, columns) do
    case update_columns(form, columns) do
      { :ok, _ } ->
        json(conn, %{
          success: true,
          url: forms_path(conn, :show, form),
          message: "Columns updated!"
        })
      { :error, changeset} ->
        conn
        |> put_status(400)
        |> json(%{
          success: false,
          message: changeset.errors
        })
    end

  end

end

web/views/form_columns_view.ex
defmodule Formerer.FormColumnsView do
  use Formerer.Web, :view
  import Formerer.ColumnFormatter

  def submission_fields(submission) do
    Map.keys(submission.fields)
  end

  def field_key_as_atom(key) do
    String.to_atom(key)
  end

end

web/templates/form_columns/edit.html.eex
<div class="mdl-card mdl-shadow--2dp">
  <div class="mdl-card__title">
    <h4 class="mdl-card__title-text">
      Show/Hide Columns
    </h4>
  </div>

  <div class="mdl-card__supporting-text">
    <p>Choose which columns to hide and show from the fields present in the last submission received</p>
    <%= form_for @conn, forms_form_columns_path(@conn, :update, @form), [name: :columns], fn f -> %>
      <%= for field <- submission_fields(@submission) do %>
        <%= label(f, field_key_as_atom(field), class: "mdl-switch mdl-js-switch") do %>
          <%= checkbox(f, field_key_as_atom(field), class: "mdl-switch__input", value: Enum.member?(@form.columns, field)) %>
          <span class="mdl-switch__label"><%= pretty_column_name(field) %></span>
        <% end %>
      <% end %>

      <div class="align-center">
        <%= submit "Select", class: "mdl-button mdl-button--raised mdl-button--colored update-columns", data: [behaviour: "submit-form"] %>
      </div>
    <% end %>
  </div>
</div>