web/router.ex
defmodule Formerer.Router do
  use Formerer.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :authenticate_user do
    plug Formerer.UserAuthentication
  end

  pipeline :activated_account do
    plug Formerer.AccountActivation
  end

  scope "/form", Formerer do
    pipe_through :api

    post "/:slug", FormSubmissionsController, :create
  end

  scope "/", Formerer do
    pipe_through [:browser, :protect_from_forgery]

    get "/", PageController, :index

    get "/register", UsersController, :new
    post "/register", UsersController, :create

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete
    resources "/account_activation", AccountActivationController, only: [:edit]
    resources "/password_reset", PasswordResetController, only: [:new, :create, :edit, :update]

    pipe_through :authenticate_user
    get "/dashboard", DashboardController, :index
    pipe_through :activated_account
    resources "/users", UsersController, only: [:edit, :update]

    resources "/forms", FormsController, only: [:new, :create, :update, :show, :delete] do
      get "/columns/edit", FormColumnsController, :edit
      post "/columns/update", FormColumnsController, :update
    end

    get "/forms/:form_id/settings", FormSettingsController, :edit

  end

  if Mix.env == :dev do
      scope "/dev" do
      pipe_through [:browser]

      forward "/mailbox", Plug.Swoosh.MailboxPreview, [base_path: "/dev/mailbox"]
    end
  end

end

web/views/shared_view.ex
import Formerer.Router.Helpers

defmodule Formerer.SharedView do
  import Ecto.Query
  use Formerer.Web, :view
  alias Formerer.Form
  alias Formerer.Repo

  def user_forms(conn) do
    user_id = current_user(conn).id

    Form
    |> where(user_id: ^user_id)
    |> Repo.all
  end

end

web/templates/shared/header.html.eex
<header class="mdl-layout__header">
  <div class="mdl-layout__header-row">
    <span class="mdl-layout-title">Formerer</span>
    <div class="mdl-layout-spacer"></div>

    <nav class="mdl-navigation">
      <%= if logged_in?(@conn) do %>
        <%= link current_user(@conn).email, to: users_path(@conn, :edit, current_user(@conn)), class: "mdl-navigation__link" %>
        <%= link "Logout", to: session_path(@conn, :delete), method: :delete, class: "mdl-navigation__link" %>
      <% else %>
        <%= link "Login", to: session_path(@conn, :new), class: "mdl-navigation__link" %>
        <%= link "Register", to: users_path(@conn, :new), class: "mdl-navigation__link" %>
      <% end %>
    </nav>
  </div>
</header>

web/templates/shared/side_nav.html.eex
<%= if logged_in?(@conn) do %>
  <div class="mdl-layout__drawer sidenav-menu">
    <span class="mdl-layout-title">Your Forms</span>
    <nav class="mdl-navigation">
      <%= for form <- user_forms(@conn) do %>
        <%= link to: forms_path(@conn, :show, form), class: "mdl-navigation__link" do %>
          <%= form.name %>
          <i class="material-icons">book</i>
        <% end %>
      <% end %>
      <%= link to: forms_path(@conn, :new), class: "mdl-navigation__link new-form-link" do %>
        New Form
        <i class="material-icons">add_circle</i>
      <% end %>
    </nav>
  </div>
<% end %>