web/router.ex
defmodule Formerer.Router do
  use Formerer.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :authenticate_user do
    plug Formerer.UserAuthentication
  end

  pipeline :activated_account do
    plug Formerer.AccountActivation
  end

  scope "/form", Formerer do
    pipe_through :api

    post "/:slug", FormSubmissionsController, :create
  end

  scope "/", Formerer do
    pipe_through [:browser, :protect_from_forgery]

    get "/", PageController, :index

    get "/register", UsersController, :new
    post "/register", UsersController, :create

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete
    resources "/account_activation", AccountActivationController, only: [:edit]
    resources "/password_reset", PasswordResetController, only: [:new, :create, :edit, :update]

    pipe_through :authenticate_user
    get "/dashboard", DashboardController, :index
    pipe_through :activated_account
    resources "/users", UsersController, only: [:edit, :update]

    resources "/forms", FormsController, only: [:new, :create, :update, :show, :delete] do
      get "/columns/edit", FormColumnsController, :edit
      post "/columns/update", FormColumnsController, :update
    end

    get "/forms/:form_id/settings", FormSettingsController, :edit

  end

  if Mix.env == :dev do
      scope "/dev" do
      pipe_through [:browser]

      forward "/mailbox", Plug.Swoosh.MailboxPreview, [base_path: "/dev/mailbox"]
    end
  end

end

web/controllers/forms_controller.ex
defmodule Formerer.FormsController do
  use Formerer.Web, :controller

  alias Formerer.{Form, FormCreator}
  import Formerer.Session, only: [current_user: 1]
  import Formerer.UserFormRetriever

  def new(conn, _) do
    changeset = Form.changeset(%Form{})
    render conn, changeset: changeset
  end

  def show(conn, %{"id" => id}) do
    case current_user(conn) |> get_user_form(id) do
      { :ok, form } ->
        form = form |> Repo.preload(:submissions)
        render conn, form: form
      { :error, error } ->
        send_resp(conn, 404, error)
    end
  end

  def create(conn, %{ "form" => form_params }) do
    changeset = Form.changeset(%Form{ identifier: "temp", user_id: current_user(conn).id }, form_params)

    case FormCreator.create(changeset, Formerer.Repo) do
      { :ok, form } ->
        conn
        |> put_flash(:info, "Form Created!")
        |> redirect(to: forms_path(conn, :show, form))
      { :error, changeset } ->
        conn
        |> put_flash(:info, "Error creating form")
        |> render("new.html", changeset: changeset)
    end
  end

  def update(conn, %{ "name" => name, "id" => id }) do
    case current_user(conn) |> get_user_form(id) do
      { :ok, form } ->
        changeset = Form.changeset(form, %{ name: name })
        form_update(conn, changeset)
      { :error, error } ->
        send_resp(conn, 404, error)
    end
  end

  def delete(conn, %{ "id" => id }) do
    case current_user(conn) |> get_user_form(id) do
      { :error, error } ->
        send_resp(conn, 404, error)
      { :ok, form } ->
        case Repo.delete(form) do
          { :ok, _ } ->
            redirect(conn, to: dashboard_path(conn, :index))
          { :error, form } ->
            send_resp(conn, 400, form)
        end
    end
  end

  defp form_update(conn, changeset) do
    case Repo.update(changeset) do
      { :ok, _ } ->
        send_resp(conn, 200, "OK")
      { :error, _ } ->
        send_resp(conn, 400, "Error updating name")
    end

  end
end

web/views/forms_view.ex
defmodule Formerer.FormsView do
  use Formerer.Web, :view
end

web/templates/forms/new.html.eex
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--4-col"></div>
  <div class="mdl-cell mdl-card mdl-shadow--2dp mdl-cell--4-col">
    <div class="mdl-card__title">
      <h2 class="mdl-card__title-text">New Form</h2>
    </div>

    <div class="mdl-card__supporting-text">

      <%= form_for @changeset, forms_path(@conn, :create), fn f -> %>

        <%= if f.errors != [] do %>
          <div class='alert'>
            <ul>
              <%= for { attr, message } <- f.errors do %>
                <li><%= humanize(attr) %> <%= translate_error(message) %></li>
              <% end %>
          </div>
        <% end %>

        <div class='mdl-textfield mdl-js-textfield'>
          <%= text_input f, :name, class: "mdl-textfield__input" %>
          <label class='mdl-textfield__label'>Name</label>
        </div>

        <%= submit "Create", class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
      <% end %>

    </div>
  </div>
</div>

web/templates/forms/show.html.eex
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--3-col"></div>
  <div class="mdl-cell mdl-card mdl-shadow--2dp mdl-cell--6-col">
    <div class="mdl-card__title">
      <h4 class="mdl-card__title-text">
        Form -&nbsp;
        <span data-token="<%= get_csrf_token %>" data-url="<%= forms_path(@conn, :update, @form) %>" data-behaviour="form-name">
          <%= @form.name %>
        </span>
        &nbsp;
        <button class="mdl-button mdl-button--icon" data-behaviour="edit-form-name">
          <i class="material-icons">edit</i>
        </button>
      </h4>
    </div>

    <div class="mdl-card__supporting-text">
      <div>
        <div class="mdl-textfield form-endpoint-url">
          <input id="form-endpoint-url" type="text" class="mdl-textfield__input" disabled value="<%= form_submissions_url(@conn, :create, @form.identifier) %>" />
        </div>
        <button id="endpoint-copy-button" data-behaviour="clipboard-copy" data-clipboard-target="#form-endpoint-url" class="mdl-button mdl-button--fab mdl-button--mini-fab mdl-button--colored">
          <i class="material-icons">content_copy</i>
        </button>
      </div>
      <p class='copied-notice'>Copied!</p>
    </div>

    <div class="mdl-card__menu">
      <a href="<%= form_settings_path(@conn, :edit, @form) %>" class="mdl-button mdl-button--icon">
        <i class="material-icons">settings</i>
      </a>
    </div>
  </div>
</div>

<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--3-col"></div>
  <div class="mdl-cell mdl-card submissions-card mdl-shadow--2dp mdl-cell--6-col">
    <%= content_tag( :div, id: "form-submissions", data: [form_id: @form.id]) do %>
      <div class="mdl-card__supporting-text" id="no-submissions-present">
        <p class="advice-text">You've not had any submissions yet, submit a form using the above URL to see it here</p>
      </div>
      <div id="submissions-present">
        <%= render Formerer.SubmissionsView, "submissions.html", conn: @conn, form: @form, submissions: @form.submissions %>
      </div>
    <% end %>
  </div>
</div>

<script>
  window.formId = <%= @form.id %>;
</script>